Use __import__ for generateDS to handle FS case issues
While mounting the source tree from an OSX 10.10 host
over boot2docker to an Ubuntu container, Bio-Formats
builds failed with:

```
Traceback (most recent call last):
  File "./xsd-fu", line 45, in <module>
    from ome.modeltools import generateds
  File "/opt/tmp/components/bioformats/components/xsd-fu/python/ome/modeltools/generateds.py", line 6, in <module>
    from generateDS.generateDS import XschemaHandler, set_type_constants
  File "/opt/tmp/components/bioformats/components/xsd-fu/python/ome/modeltools/generateDS.py", line 6, in <module>
    from generateDS.generateDS import XschemaHandler, set_type_constants
ImportError: No module named generateDS
```

since there is a case-insensitive clash between our
ome.model.generateds (imported relatively) and
generateDS.generateDS (imported absolutely).